FROM ubuntu:bionic
CMD ["supervisord", "-c", "/etc/supervisor.conf"]
COPY ./supervisor.conf /etc/supervisor.conf
ENV DEBIAN_FRONTEND=noninteractive
VOLUME /opt/hydrus/db XVFBRES=1680x1050x16

RUN echo "Europe/Dublin" > /etc/timezone && apt-get update && apt-get install -y curl xvfb libxcb1 libgdk-pixbuf2.0-0 x11vnc supervisor fvwm ffmpeg fonts-takao-mincho fonts-takao ttf-ancient-fonts && apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN curl -s -L https://github.com/hydrusnetwork/hydrus/releases/download/v$(curl -s https://api.github.com/repos/hydrusnetwork/hydrus/releases/latest | grep 'tag_name' | cut -d\" -f4 | cut -c 2-)/Hydrus.Network.$(curl -s https://api.github.com/repos/hydrusnetwork/hydrus/releases/latest | grep 'tag_name' | cut -d\" -f4 | cut -c 2-).-.Linux.-.Executable.tar.gz | tar xzf - --strip-components=1 -C /opt/hydrus