FROM legsplits/hydrus-base:archlinux-base
CMD ["supervisord", "-c", "/etc/supervisor.conf"]
COPY ./supervisor-source.conf /etc/supervisor.conf
VOLUME /opt/hydrus/db
LABEL git="https://github.com/hydrusnetwork/hydrus"
ENV XVFBRES=1680x1050x16
RUN curl -s -L https://github.com/hydrusnetwork/hydrus/archive/master.tar.gz | tar xzf - --strip-components=1 -C /opt/hydrus