FROM legsplits/hydrus-base:ubuntu-base
CMD ["supervisord", "-c", "/etc/supervisor.conf"]
COPY ./supervisor.conf /etc/supervisor.conf
ENV XVFBRES=1680x1050x16
LABEL git="https://github.com/hydrusnetwork/hydrus"
VOLUME /opt/hydrus/db

RUN curl -s -L https://github.com/hydrusnetwork/hydrus/releases/download/v$(curl -s https://api.github.com/repos/hydrusnetwork/hydrus/releases/latest | grep 'tag_name' | cut -d\" -f4 | cut -c 2-)/Hydrus.Network.$(curl -s https://api.github.com/repos/hydrusnetwork/hydrus/releases/latest | grep 'tag_name' | cut -d\" -f4 | cut -c 2-).-.Linux.-.Executable.tar.gz | tar xzf - --strip-components=1 -C /opt/hydrus