FROM ubuntu:rolling
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "Europe/Dublin" > /etc/timezone && \
  apt-get update && \
  apt-get install -y libxcb1 libgdk-pixbuf2.0-0 libcurl4-openssl-dev libssl-dev libsdl1.2-dev \
  gstreamer-1.0  libgstreamer-plugins-base1.0-dev v4l-utils freeglut3-dev \
  libgtk-3-dev libglw1-mesa libglw1-mesa-dev python-dev python3-wxgtk4.0 \
  python3-pip python3-setuptools python3-send2trash python3-bs4 \
  python3-chardet python3-html5lib python3-lxml python3-setuptools \
  python3-requests python3-urllib3  python3-openssl python3-httmock \
  python3-lz4 python3-matplotlib python3-mock python-socksipychain \
  python-lzma python3-numpy python3-psutil python3-twisted python3-yaml \
  python3-willow python-pathlib2 xvfb fonts-takao-mincho fonts-takao \
  ttf-ancient-fonts ffmpeg x11vnc fvwm supervisor python-wxtools